# Generated by Django 5.0.6 on 2024-05-30 07:36

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Food',
            fields=[
                ('food_no', models.AutoField(primary_key=True, serialize=False)),
                ('writer', models.CharField(max_length=50)),
                ('title', models.CharField(max_length=255)),
                ('content', models.TextField()),
                ('food_type', models.CharField(max_length=100)),
                ('area_name', models.CharField(max_length=255)),
                ('regist_date', models.DateTimeField()),
                ('modify_date', models.DateTimeField()),
                ('see_cnt', models.IntegerField(default=0)),
                ('member_idx', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
