# Generated by Django 4.0.4 on 2024-05-30 01:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sports', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='BaseballTeam',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('summary', models.CharField(max_length=255, null=True)),
                ('hometown', models.CharField(max_length=255, null=True)),
                ('stadium', models.CharField(max_length=255, null=True)),
                ('manager', models.CharField(max_length=255, null=True)),
                ('color1', models.CharField(max_length=8)),
                ('color2', models.CharField(max_length=8)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='FootballPost',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('author', models.CharField(max_length=255)),
                ('content', models.TextField()),
                ('wdate', models.DateTimeField()),
                ('udate', models.DateTimeField()),
                ('views', models.IntegerField()),
                ('comment', models.IntegerField(default=0)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='FootballTeam',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('summary', models.CharField(max_length=255, null=True)),
                ('hometown', models.CharField(max_length=255, null=True)),
                ('stadium', models.CharField(max_length=255, null=True)),
                ('manager', models.CharField(max_length=255, null=True)),
                ('color1', models.CharField(max_length=8)),
                ('color2', models.CharField(max_length=8)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='SportsEtcPost',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('author', models.CharField(max_length=255)),
                ('content', models.TextField()),
                ('wdate', models.DateTimeField()),
                ('udate', models.DateTimeField()),
                ('views', models.IntegerField()),
                ('comment', models.IntegerField(default=0)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='SportsEtcTeam',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('summary', models.CharField(max_length=255, null=True)),
                ('hometown', models.CharField(max_length=255, null=True)),
                ('stadium', models.CharField(max_length=255, null=True)),
                ('manager', models.CharField(max_length=255, null=True)),
                ('color1', models.CharField(max_length=8)),
                ('color2', models.CharField(max_length=8)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='SportsEtcPostComment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('author', models.CharField(max_length=255)),
                ('content', models.CharField(max_length=255)),
                ('wdate', models.DateTimeField()),
                ('post_id', models.ForeignKey(db_column='post_id', on_delete=django.db.models.deletion.CASCADE, related_name='post', to='sports.sportsetcpost')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='SportsEtcPlayer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('summary', models.CharField(max_length=255, null=True)),
                ('stadium', models.DateTimeField(null=True)),
                ('team', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='team', to='sports.sportsetcteam')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='FootballPostComment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('author', models.CharField(max_length=255)),
                ('content', models.CharField(max_length=255)),
                ('wdate', models.DateTimeField()),
                ('post_id', models.ForeignKey(db_column='post_id', on_delete=django.db.models.deletion.CASCADE, related_name='post', to='sports.footballpost')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='FootballPlayer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('summary', models.CharField(max_length=255, null=True)),
                ('stadium', models.DateTimeField(null=True)),
                ('team', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='team', to='sports.footballteam')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='BaseballPlayer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('summary', models.CharField(max_length=255, null=True)),
                ('stadium', models.DateTimeField(null=True)),
                ('team', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='team', to='sports.baseballteam')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
