# Generated by Django 4.0.4 on 2024-05-30 15:04

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('sports', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SportsPlayer',
            fields=[
                ('player_id', models.AutoField(primary_key=True, serialize=False)),
                ('player_name', models.CharField(max_length=255)),
                ('player_game', models.CharField(max_length=64)),
                ('player_birthdate', models.DateField(null=True)),
                ('player_intro', models.CharField(max_length=255, null=True)),
                ('player_uniform_number', models.IntegerField(null=True)),
                ('player_fans', models.ManyToManyField(related_name='liked_player', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='SportsPlayerTalk',
            fields=[
                ('player_talk_id', models.AutoField(primary_key=True, serialize=False)),
                ('player_talk_author', models.CharField(max_length=255)),
                ('player_content', models.CharField(max_length=255)),
                ('player_wdate', models.DateTimeField()),
                ('member_idx', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('player_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sports.sportsplayer')),
            ],
        ),
        migrations.CreateModel(
            name='SportsPost',
            fields=[
                ('post_id', models.AutoField(primary_key=True, serialize=False)),
                ('post_game', models.CharField(max_length=64)),
                ('post_author', models.CharField(max_length=255)),
                ('post_author_nn', models.CharField(default=models.CharField(max_length=255), max_length=255, null=True)),
                ('post_title', models.CharField(max_length=255)),
                ('post_content', models.TextField()),
                ('post_wdate', models.DateTimeField()),
                ('post_udate', models.DateTimeField()),
                ('post_views', models.IntegerField()),
                ('post_dislike', models.ManyToManyField(related_name='disliked_post', to=settings.AUTH_USER_MODEL)),
                ('post_like', models.ManyToManyField(related_name='liked_post', to=settings.AUTH_USER_MODEL)),
                ('post_member_idx', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='SportsReply',
            fields=[
                ('reply_id', models.AutoField(primary_key=True, serialize=False)),
                ('reply_author', models.CharField(max_length=255)),
                ('reply_author_nn', models.CharField(default=models.CharField(max_length=255), max_length=255, null=True)),
                ('reply_content', models.CharField(max_length=255)),
                ('reply_wdate', models.DateTimeField()),
                ('post_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sports.sportspost')),
                ('reply_dislike', models.ManyToManyField(related_name='disliked_reply', to=settings.AUTH_USER_MODEL)),
                ('reply_like', models.ManyToManyField(related_name='liked_reply', to=settings.AUTH_USER_MODEL)),
                ('reply_member_idx', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='SportsTeam',
            fields=[
                ('team_id', models.AutoField(primary_key=True, serialize=False)),
                ('team_name', models.CharField(max_length=255)),
                ('team_game', models.CharField(max_length=64)),
                ('team_intro', models.CharField(max_length=255, null=True)),
                ('team_hometown', models.CharField(max_length=255, null=True)),
                ('team_manager', models.CharField(max_length=255, null=True)),
                ('team_site', models.CharField(max_length=512, null=True)),
                ('team_color1', models.CharField(max_length=16, null=True)),
                ('team_color2', models.CharField(max_length=16, null=True)),
                ('team_color3', models.CharField(max_length=16, null=True)),
                ('team_color4', models.CharField(max_length=16, null=True)),
                ('team_fans', models.ManyToManyField(related_name='liked_team', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='SportsTeamTalk',
            fields=[
                ('team_talk_id', models.AutoField(primary_key=True, serialize=False)),
                ('team_talk_author', models.CharField(max_length=255)),
                ('team_talk_content', models.CharField(max_length=255)),
                ('team_talk_wdate', models.DateTimeField()),
                ('member_idx', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('team_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sports.sportsteam')),
            ],
        ),
        migrations.RemoveField(
            model_name='baseballplayerfanrelation',
            name='player',
        ),
        migrations.RemoveField(
            model_name='baseballplayertalk',
            name='player',
        ),
        migrations.RemoveField(
            model_name='baseballpostcomment',
            name='post_id',
        ),
        migrations.RemoveField(
            model_name='baseballteamfanrelation',
            name='team',
        ),
        migrations.RemoveField(
            model_name='baseballteamtalk',
            name='team',
        ),
        migrations.RemoveField(
            model_name='footballplayer',
            name='team',
        ),
        migrations.RemoveField(
            model_name='footballplayerfanrelation',
            name='player',
        ),
        migrations.RemoveField(
            model_name='footballplayertalk',
            name='player',
        ),
        migrations.RemoveField(
            model_name='footballpostcomment',
            name='post_id',
        ),
        migrations.RemoveField(
            model_name='footballteamfanrelation',
            name='team',
        ),
        migrations.RemoveField(
            model_name='footballteamtalk',
            name='team',
        ),
        migrations.RemoveField(
            model_name='sportsetcplayer',
            name='team',
        ),
        migrations.RemoveField(
            model_name='sportsetcplayerfanrelation',
            name='player',
        ),
        migrations.RemoveField(
            model_name='sportsetcplayertalk',
            name='player',
        ),
        migrations.RemoveField(
            model_name='sportsetcpostcomment',
            name='post_id',
        ),
        migrations.RemoveField(
            model_name='sportsetcteamfanrelation',
            name='team',
        ),
        migrations.RemoveField(
            model_name='sportsetcteamtalk',
            name='team',
        ),
        migrations.DeleteModel(
            name='BaseballPlayer',
        ),
        migrations.DeleteModel(
            name='BaseballPlayerFanRelation',
        ),
        migrations.DeleteModel(
            name='BaseballPlayerTalk',
        ),
        migrations.DeleteModel(
            name='BaseballPost',
        ),
        migrations.DeleteModel(
            name='BaseballPostComment',
        ),
        migrations.DeleteModel(
            name='BaseballTeam',
        ),
        migrations.DeleteModel(
            name='BaseballTeamFanRelation',
        ),
        migrations.DeleteModel(
            name='BaseballTeamTalk',
        ),
        migrations.DeleteModel(
            name='FootballPlayer',
        ),
        migrations.DeleteModel(
            name='FootballPlayerFanRelation',
        ),
        migrations.DeleteModel(
            name='FootballPlayerTalk',
        ),
        migrations.DeleteModel(
            name='FootballPost',
        ),
        migrations.DeleteModel(
            name='FootballPostComment',
        ),
        migrations.DeleteModel(
            name='FootballTeam',
        ),
        migrations.DeleteModel(
            name='FootballTeamFanRelation',
        ),
        migrations.DeleteModel(
            name='FootballTeamTalk',
        ),
        migrations.DeleteModel(
            name='SportsEtcPlayer',
        ),
        migrations.DeleteModel(
            name='SportsEtcPlayerFanRelation',
        ),
        migrations.DeleteModel(
            name='SportsEtcPlayerTalk',
        ),
        migrations.DeleteModel(
            name='SportsEtcPost',
        ),
        migrations.DeleteModel(
            name='SportsEtcPostComment',
        ),
        migrations.DeleteModel(
            name='SportsEtcTeam',
        ),
        migrations.DeleteModel(
            name='SportsEtcTeamFanRelation',
        ),
        migrations.DeleteModel(
            name='SportsEtcTeamTalk',
        ),
        migrations.AddField(
            model_name='sportsplayer',
            name='team_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='sports.sportsteam'),
        ),
    ]
