# Generated by Django 4.0.4 on 2024-05-31 02:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sports', '0002_sportsplayer_sportsplayertalk_sportspost_sportsreply_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='sportsplayer',
            old_name='team_id',
            new_name='player_team',
        ),
        migrations.RenameField(
            model_name='sportsplayertalk',
            old_name='member_idx',
            new_name='player_talk_member',
        ),
        migrations.RenameField(
            model_name='sportsplayertalk',
            old_name='player_id',
            new_name='player_talk_player',
        ),
        migrations.RenameField(
            model_name='sportspost',
            old_name='post_member_idx',
            new_name='post_member',
        ),
        migrations.RenameField(
            model_name='sportsreply',
            old_name='reply_member_idx',
            new_name='reply_member',
        ),
        migrations.RenameField(
            model_name='sportsteamtalk',
            old_name='member_idx',
            new_name='team_talk_member',
        ),
        migrations.RenameField(
            model_name='sportsteamtalk',
            old_name='team_id',
            new_name='team_talk_team',
        ),
    ]
