# Generated by Django 4.0.4 on 2024-05-31 13:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sports', '0004_alter_sportspost_post_author_nn'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sportspost',
            name='post_author_nn',
            field=models.CharField(max_length=255),
        ),
    ]
