# Generated by Django 5.0.6 on 2024-05-29 04:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('economy', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='border',
            name='댓글수',
        ),
        migrations.RemoveField(
            model_name='border',
            name='싫어요',
        ),
        migrations.RemoveField(
            model_name='border',
            name='좋아요',
        ),
    ]
