# Generated by Django 5.0.6 on 2024-05-29 05:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('economy', '0002_remove_border_댓글수_remove_border_싫어요_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='border',
            old_name='내용',
            new_name='contents',
        ),
        migrations.RenameField(
            model_name='border',
            old_name='조회수',
            new_name='hits',
        ),
        migrations.RenameField(
            model_name='border',
            old_name='제목',
            new_name='title',
        ),
        migrations.RenameField(
            model_name='border',
            old_name='수정일',
            new_name='updatetime',
        ),
        migrations.RenameField(
            model_name='border',
            old_name='작성자',
            new_name='writer',
        ),
        migrations.RenameField(
            model_name='border',
            old_name='작성일',
            new_name='writetime',
        ),
    ]
